"""
配置管理 / Configuration Management
=====================================
从环境变量（.env 文件）加载所有配置。
Loads all configuration from environment variables (.env file).

使用方法 / Usage:
    from config import settings
    print(settings.privy_app_id)
"""

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """
    应用配置类，使用 Pydantic Settings 自动从环境变量加载。
    Application settings, automatically loaded from environment variables via Pydantic Settings.

    所有字段都有对应的环境变量名（大写），详见 .env.example。
    All fields correspond to environment variable names (uppercase), see .env.example.
    """

    model_config = SettingsConfigDict(
        # 从项目根目录的 .env 文件加载 / Load from .env file in project root
        env_file="../.env",
        env_file_encoding="utf-8",
        # 忽略未声明的额外字段 / Ignore undeclared extra fields
        extra="ignore",
    )

    # ----------------------------------------------------------
    # Privy 配置 / Privy Configuration
    # ----------------------------------------------------------

    # Privy App ID（公开值）/ Privy App ID (public value)
    privy_app_id: str

    # Privy App Secret（服务端私密）/ Privy App Secret (server-only secret)
    privy_app_secret: str

    # P256 授权私钥，格式：wallet-auth:<base64 PKCS8 DER>
    # P256 authorization private key, format: wallet-auth:<base64 PKCS8 DER>
    # 由 python scripts/generate_auth_key.py 生成 / Generated by scripts/generate_auth_key.py
    privy_authorization_key: str

    # Key Quorum ID（在 Privy Dashboard 注册公钥后获得）
    # Key Quorum ID (obtained after registering public key in Privy Dashboard)
    privy_key_quorum_id: str

    # ----------------------------------------------------------
    # Polymarket / CLOB API 配置 / Polymarket / CLOB API Configuration
    # ----------------------------------------------------------

    # Polygon 主网 RPC URL / Polygon mainnet RPC URL
    polymarket_rpc_url: str = "https://polygon-rpc.com"

    # 链 ID（137 = Polygon 主网）/ Chain ID (137 = Polygon mainnet)
    polymarket_chain_id: int = 137

    # Polymarket CLOB API 地址 / Polymarket CLOB API host
    polymarket_clob_host: str = "https://clob.polymarket.com"

    # CTF Exchange 合约地址（标准市场）/ CTF Exchange contract address (standard markets)
    polymarket_ctf_exchange_address: str = "0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E"

    # NegRisk CTF Exchange 合约地址（多结果市场）/ NegRisk CTF Exchange contract (multi-outcome markets)
    polymarket_neg_risk_ctf_exchange_address: str = "0xC5d563A36AE78145C45a50134d48A1215220f80a"

    # ----------------------------------------------------------
    # FastAPI 服务器配置 / FastAPI Server Configuration
    # ----------------------------------------------------------

    # 服务器监听地址 / Server host
    api_host: str = "0.0.0.0"

    # 服务器监听端口 / Server port
    api_port: int = 8000

    # 调试模式 / Debug mode
    debug: bool = False

    # ----------------------------------------------------------
    # Privy API Base URLs
    # ----------------------------------------------------------

    # Privy REST API 基础地址 / Privy REST API base URL
    privy_api_base_url: str = "https://api.privy.io/v1"

    @property
    def privy_auth_header(self) -> str:
        """
        生成 HTTP Basic Auth 头的 base64 编码值。
        Generates base64-encoded value for HTTP Basic Auth header.

        格式 / Format: base64(app_id:app_secret)
        """
        import base64
        credentials = f"{self.privy_app_id}:{self.privy_app_secret}"
        return base64.b64encode(credentials.encode()).decode()


# 全局单例配置实例 / Global singleton settings instance
# 在整个应用中通过 from config import settings 使用
# Use throughout the app with: from config import settings
settings = Settings()
