"""
Polymarket CLOB API 客户端 / Polymarket CLOB API Client
=========================================================
封装与 Polymarket CLOB（Central Limit Order Book）API 的交互。
Encapsulates interactions with the Polymarket CLOB (Central Limit Order Book) API.

主要功能 / Main Functions:
    - get_market: 获取市场信息（token_id, tick_size, fee_rate 等）
    - get_fee_rate: 获取指定 token 的当前手续费率
    - submit_order: 提交已签名的订单到 CLOB
    - get_open_orders: 查询用户的挂单列表

API 认证 / API Authentication:
    - 公开接口（市场信息等）：无需认证 / Public endpoints (market info etc.): no auth needed
    - 受保护接口（下单、查询）：需要 L2 HMAC 认证
      Protected endpoints (orders, queries): require L2 HMAC auth

CLOB API 文档 / CLOB API Docs:
    https://docs.polymarket.com/developers/CLOB/overview
"""

import json

import httpx

from config import settings
from polymarket.clob_auth import build_l2_headers


class ClobApiClient:
    """
    Polymarket CLOB API 客户端。
    Polymarket CLOB API client.

    使用方法 / Usage:
        clob = ClobApiClient(api_key="...", api_secret="...", api_passphrase="...")
        market = clob.get_market("condition_id_here")
        fee_rate = clob.get_fee_rate(token_id)
        result = clob.submit_order(signed_order, order_type="GTC")
    """

    def __init__(
        self,
        api_key: str = "",
        api_secret: str = "",
        api_passphrase: str = "",
    ):
        """
        Args:
            api_key: CLOB API Key（L2 认证用，只有受保护接口才需要）
                     CLOB API Key (for L2 auth, only needed for protected endpoints)
            api_secret: CLOB API Secret / CLOB API Secret
            api_passphrase: CLOB API Passphrase / CLOB API Passphrase
        """
        self.base_url = settings.polymarket_clob_host
        self._api_key = api_key
        self._api_secret = api_secret
        self._api_passphrase = api_passphrase

    def get_market(self, condition_id: str) -> dict:
        """
        获取市场信息（公开接口，无需认证）。
        Gets market information (public endpoint, no auth needed).

        返回的市场信息包含下单必需的字段：
        Returned market info contains fields required for placing orders:
            - tokens: 包含 token_id（BUY/SELL 对应不同 token）/ Contains token_id (different tokens for BUY/SELL)
            - minimum_order_size: 最小下单金额 / Minimum order size
            - minimum_tick_size: 最小价格精度 / Minimum price tick size
            - neg_risk: 是否为多结果市场 / Whether it's a multi-outcome market

        Args:
            condition_id: Polymarket 市场的条件 ID（32 字节十六进制）
                          Polymarket market condition ID (32-byte hex)

        Returns:
            市场详情字典 / Market details dictionary

        Raises:
            httpx.HTTPStatusError: 如果市场不存在或 API 错误 / If market not found or API error
        """
        with httpx.Client() as client:
            response = client.get(
                f"{self.base_url}/markets/{condition_id}",
                headers={"Content-Type": "application/json"},
            )
            response.raise_for_status()
            return response.json()

    def get_fee_rate(self, token_id: str) -> int:
        """
        获取指定市场 token 的当前手续费率（基点）。
        Gets the current fee rate (basis points) for a market token.

        重要：每次构建订单前必须动态获取费率，不能硬编码！
        Important: Must dynamically fetch fee rate before each order build, cannot hardcode!

        Args:
            token_id: 市场结果 token 的 ID / Market outcome token ID

        Returns:
            手续费率（整数基点，如 100 = 1%）/ Fee rate (integer bps, e.g., 100 = 1%)
        """
        with httpx.Client() as client:
            response = client.get(
                f"{self.base_url}/fee-rate",
                params={"token_id": token_id},
                headers={"Content-Type": "application/json"},
            )
            response.raise_for_status()
            data = response.json()

        # CLOB API 返回字符串格式的 fee rate，转换为整数
        # CLOB API returns fee rate as string, convert to integer
        return int(float(data.get("fee_rate", "0")) * 10000)  # 转换为基点 / Convert to bps

    def submit_order(
        self,
        signed_order: dict,
        order_type: str = "GTC",
        wallet_address: str = "",
        builder_headers: dict = None,
    ) -> dict:
        """
        提交已签名的订单到 Polymarket CLOB。
        Submits a signed order to the Polymarket CLOB.

        订单类型 / Order Types:
            GTC (Good-Till-Cancelled): 挂单直到成交或手动取消（最常用）
                                       Resting order until filled or manually cancelled (most common)
            GTD (Good-Till-Date): 挂单直到指定时间 / Resting until specified time
            FOK (Fill-Or-Kill): 立即全部成交或全部取消 / Immediate all-or-nothing fill
            FAK (Fill-And-Kill): 立即成交可成交部分，余量取消 / Fill available amount, cancel rest

        Args:
            signed_order: 由 build_signed_order_payload() 生成的签名订单
                          Signed order generated by build_signed_order_payload()
            order_type: 订单类型，默认 GTC / Order type, default GTC
            wallet_address: 下单的钱包地址（用于 L2 头）/ Wallet address (for L2 header)
            builder_headers: Builder 方案额外的认证头（POLY_BUILDER_*）。
                             如果提供，则同时携带 L2 头 + Builder 头。
                             Extra Builder auth headers (POLY_BUILDER_*).
                             When provided, both L2 headers + Builder headers are sent.

        Returns:
            CLOB API 响应，包含 orderID 等信息 / CLOB API response with orderID etc.

        Raises:
            httpx.HTTPStatusError: 如果订单被拒绝 / If order is rejected
        """
        if not all([self._api_key, self._api_secret, self._api_passphrase]):
            raise ValueError(
                "提交订单需要 L2 API 凭据 / "
                "Submitting orders requires L2 API credentials"
            )

        request_path = "/order"
        body_data = {
            "order": signed_order,
            # owner 字段必须等于 API Key（参考 py-clob-client order_to_json）
            # owner field must equal API Key (per py-clob-client order_to_json)
            "owner": self._api_key,
            "orderType": order_type,
            "postOnly": False,
        }
        body_str = json.dumps(body_data, separators=(",", ":"))

        # 构建 L2 认证头
        # Build L2 authentication headers
        headers = build_l2_headers(
            api_key=self._api_key,
            api_secret=self._api_secret,
            api_passphrase=self._api_passphrase,
            method="POST",
            request_path=request_path,
            body=body_str,
            wallet_address=wallet_address,
        )

        # Builder 方案：合并 Builder 认证头（L2 头 + POLY_BUILDER_* 头同时携带）
        # Builder scheme: merge Builder auth headers (L2 headers + POLY_BUILDER_* headers together)
        if builder_headers:
            headers.update(builder_headers)

        with httpx.Client() as client:
            response = client.post(
                f"{self.base_url}{request_path}",
                content=body_str,
                headers=headers,
            )
            response.raise_for_status()
            return response.json()

    def get_open_orders(self, wallet_address: str) -> list[dict]:
        """
        查询用户的当前挂单列表。
        Queries user's current open orders.

        Args:
            wallet_address: 用户的 EOA 地址 / User's EOA address

        Returns:
            挂单列表 / List of open orders
        """
        request_path = "/data/orders"

        headers = build_l2_headers(
            api_key=self._api_key,
            api_secret=self._api_secret,
            api_passphrase=self._api_passphrase,
            method="GET",
            request_path=request_path,
        )

        with httpx.Client() as client:
            response = client.get(
                f"{self.base_url}{request_path}",
                params={"maker": wallet_address},
                headers=headers,
            )
            response.raise_for_status()
            return response.json()

    def cancel_order(self, order_id: str) -> dict:
        """
        取消指定订单。
        Cancels a specific order.

        Args:
            order_id: 订单 ID（来自 submit_order 的响应）/ Order ID (from submit_order response)

        Returns:
            取消结果 / Cancellation result
        """
        request_path = f"/order/{order_id}"

        headers = build_l2_headers(
            api_key=self._api_key,
            api_secret=self._api_secret,
            api_passphrase=self._api_passphrase,
            method="DELETE",
            request_path=request_path,
        )

        with httpx.Client() as client:
            response = client.delete(
                f"{self.base_url}{request_path}",
                headers=headers,
            )
            response.raise_for_status()
            return response.json()
